source/repos/MojSwiat2/MojSwiat2/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MojSwiat2.Data;
using MojSwiat2.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MojSwiat2.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private ApplicationDbContext _db;
        private IHostingEnvironment _he;

        public ProductController(ApplicationDbContext db, IHostingEnvironment he)
        {
            _db = db;
            _he = he;
        }

        public IActionResult Index()
        {
            return View(_db.Products.Include(c =>c.ProductTypes).Include(f=>f.SpecialTag).ToList());
        }


        //POST Index action method
        [HttpPost]
        public IActionResult Index(decimal? lowAmount, decimal? largeAmount)
        {
            var products = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTag).Where(c => c.Price >= lowAmount && c.Price <= largeAmount).ToList();
            if(lowAmount== null || largeAmount == null)
            {
                products = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTag).ToList();

            }
            return View(products);
        }

        //GET Create Method
        public IActionResult Create()
        {
            ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["TagId"] = new SelectList(_db.SpecialTag.ToList(),"Id", "SpecialTags");
            return View();
        }

        //Create Post action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Products products, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                var searchProduct = _db.Products.FirstOrDefault(c => c.Name == products.Name);
                if (searchProduct != null)
                {
                    ViewBag.message = "This product already exists";
                    ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
                    ViewData["TagId"] = new SelectList(_db.SpecialTag.ToList(), "Id", "SpecialTags");
                    return View(products);
                }
                if (image != null)
                {
                    var name = Path.Combine(_he.WebRootPath + "/Images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    products.Image = "Images/" + image.FileName;
                }
                if (image == null)
                {
                    products.Image = "Images/noimage.PNG";
                }
                _db.Products.Add(products);
                await _db.SaveChangesAsync();
                TempData["save"] = "Product type has been saved successfully";
                return RedirectToAction(nameof(Index));
            }

            return View(products);
        }


        //GEt Edit Action method

        public ActionResult Edit(int? id)
        {
            ViewData["productTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["TagId"] = new SelectList(_db.SpecialTag.ToList(), "Id", "SpecialTags");
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTag).FirstOrDefault(c => c.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        //POST Edit Action Method
        [HttpPost]
        public async Task<IActionResult>Edit(Products products, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    var name = Path.Combine(_he.WebRootPath + "/Images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    products.Image = "Images/" + image.FileName;
                }
                if (image == null)
                {
                    products.Image = "Images/noimage.PNG";
                }
                _db.Products.Update(products);
                await _db.SaveChangesAsync();
                TempData["save"] = "Product type has been saved successfully";
                return RedirectToAction(nameof(Index));
            }

            return View(products);
        }

        //GET Details Action Method

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.Products.Include(c => c.ProductTypes).Include(c => c.SpecialTag).FirstOrDefault(c => c.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        //GET Delete Action Method

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.Products.Include(c=> c.SpecialTag).Include(c => c.SpecialTag).Where(c => c.Id == id).FirstOrDefault();
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        //POST Delete Action Method
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.Products.FirstOrDefault(c => c.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            _db.Products.Remove(product);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

source/repos/MojSwiat2/MojSwiat2/Areas/Admin/Controllers/ProductTypesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MojSwiat2.Data;
using MojSwiat2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MojSwiat2.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductTypesController : Controller
    {

        private ApplicationDbContext _db;

        public ProductTypesController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            //var data = _db.ProductTypes.ToList()
            return View(_db.ProductTypes.ToList());
        }

        //Create Get action method
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        //Create Post action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductTypes productTypes)
        {
            if (ModelState.IsValid)
            {
                _db.ProductTypes.Add(productTypes);
                await _db.SaveChangesAsync();
                TempData["save"] = "Product type has been saved successfully";
                return RedirectToAction(nameof(Index));
            }

            return View(productTypes);
        }

        //Create Get EDIT method
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return NotFound();
            }
            return View(productType);
        }

        //Create Post EDIT action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductTypes productTypes)
        {
            if (ModelState.IsValid)
            {
                _db.Update(productTypes);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(productTypes);
        }

        //Create Get Details action method
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return NotFound();
            }
            return View(productType);
        }

        //Create Post EDIT action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Details(ProductTypes productTypes)
        {
            return RedirectToAction(nameof(Index));

            
        }

        //Create Get Delete method
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return NotFound();
            }
            return View(productType);
        }

        //Create Post Delete action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id, ProductTypes productTypes)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (id!=productTypes.Id)
            {
                return NotFound();
            }
            var productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Remove(productType);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(productTypes);
        }
    }
}

source/repos/MojSwiat2/MojSwiat2/Areas/Admin/Controllers/SpecialTagController.cs
using Microsoft.AspNetCore.Mvc;
using MojSwiat2.Data;
using MojSwiat2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MojSwiat2.Areas.Admin.Controllers
{

        [Area("Admin")]
        public class SpecialTagController : Controller
        {

            private ApplicationDbContext _db;

            public SpecialTagController(ApplicationDbContext db)
            {
                _db = db;
            }
            public IActionResult Index()
            {
                //var data = _db.SpecialTag.ToList()
                return View(_db.SpecialTag.ToList());
            }

            //Create Get action method
            public ActionResult Create()
            {
                return View();
            }

            //Create Post action Method
            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Create(SpecialTag specialTag)
            {
                if (ModelState.IsValid)
                {
                    _db.SpecialTag.Add(specialTag);
                    await _db.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }

                return View(specialTag);
            }

            //Create Get EDIT method
            public ActionResult Edit(int? id)
            {
                if (id == null)
                {
                    return NotFound();
                }
                var specialTag = _db.SpecialTag.Find(id);
                if (specialTag == null)
                {
                    return NotFound();
                }
                return View(specialTag);
            }

            //Create Post EDIT action Method
            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Edit(SpecialTag specialTag)
            {
                if (ModelState.IsValid)
                {
                    _db.Update(specialTag);
                    await _db.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }

                return View(specialTag);
            }

            //Create Get Details action method
            public ActionResult Details(int? id)
            {
                if (id == null)
                {
                    return NotFound();
                }
                var specialTags = _db.SpecialTag.Find(id);
                if (specialTags == null)
                {
                    return NotFound();
                }
                return View(specialTags);
            }

            //Create Post EDIT action Method
            [HttpPost]
            [ValidateAntiForgeryToken]
            public IActionResult Details(SpecialTag specialTag)
            {
                return RedirectToAction(nameof(Index));


            }

            //Create Get Delete method
            public ActionResult Delete(int? id)
            {
                if (id == null)
                {
                    return NotFound();
                }
                var specialTags = _db.SpecialTag.Find(id);
                if (specialTags == null)
                {
                    return NotFound();
                }
                return View(specialTags);
            }

            //Create Post Delete action Method
            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Delete(int? id, SpecialTag specialTag)
            {
                if (id == null)
                {
                    return NotFound();
                }

                if (id!=specialTag.Id)
                {
                    return NotFound();
                }
                var specialTags = _db.SpecialTag.Find(id);
                if (specialTags == null)
                {
                    return NotFound();
                }
                if (ModelState.IsValid)
                {
                    _db.Remove(specialTags);
                    await _db.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }

                return View(specialTag);
            }
        }
}

source/repos/MojSwiat2/MojSwiat2/Views/Shared/_ButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td style="width: 150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="ProductTypes" class="btn btn-primary" asp-route-id="@Model">Edytuj</a>
        <a asp-action="Details" asp-controller="ProductTypes" class="btn btn-success" asp-route-id="@Model">Szczegóły</a>
        <a asp-action="Delete" asp-controller="ProductTypes" class="btn btn-danger" asp-route-id="@Model">Usuń</a>
    </div>
</td>

source/repos/MojSwiat2/MojSwiat2/Views/Shared/_Layout.cshtml
@using System.Net.Http
@using MojSwiat2.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    var userRole = HttpContextAccessor.HttpContext.Session.GetString("roleName");
    int count = 0;
    List<Products> products = HttpContextAccessor.HttpContext.Session.Get<List<Products>>("products");
    if (products == null)
    {
        products = new List<Products>();
    }
    count = products.Count();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MojSwiat2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/2.2.2/css/buttons.dataTables.min.css" />
    <style>
        .error {
            color: red;
        }
    </style>
    <style>
        #payu-payment-form button[type=submit] {
            border: 0px;
            height: 35px;
            width: 140px;
            background: url('http://static.payu.com/pl/standard/partners/buttons/payu_account_button_long_03.png');
            background-repeat: no-repeat;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MojSwiat2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (userRole == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductTypes" asp-action="Index">Typ Produktu</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="SpecialTag" asp-action="Index">Okazja</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Produkt</a>
                            </li>

                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Cart">
                                <i class="fa-solid fa-cart-shopping"></i>
                                (@count)
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="http://agnieszkakuznecka.blogspot.com/">Mój blog</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MojSwiat - <a asp-area="" asp-controller="Home" asp-action="Privacy">Kontakt</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.9.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.5/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.5/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.print.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jQueryFixes.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

source/repos/MojSwiat2/MojSwiat2/Views/Shared/_PartialView.cshtml
@model string
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="btn-group">
    <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model">
        <i class="far fa-edit"></i>
    </a>
    <a asp-action="Details" class="btn btn-success" asp-route-id="@Model"><i class="fas fa-list-ul"></i></a>
    <a asp-action="Locout" class="btn btn-danger" asp-route-id="@Model">
        <i class="fas fa-trash-alt"></i>
    </a>
</div>

source/repos/MojSwiat2/MojSwiat2/Views/Shared/_ProductPageButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td style="width: 150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="Product" class="btn btn-primary" asp-route-id="@Model">Edytuj</a>
        <a asp-action="Details" asp-controller="Product" class="btn btn-success" asp-route-id="@Model">Sczegóły</a>
        <a asp-action="Delete" asp-controller="Product" class="btn btn-danger" asp-route-id="@Model">Usuń</a>
    </div>
</td>

source/repos/MojSwiat2/MojSwiat2/Views/Shared/_TagPageButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td style="width: 150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="SpecialTag" class="btn btn-primary" asp-route-id="@Model">Edytuj</a>
        <a asp-action="Details" asp-controller="SpecialTag" class="btn btn-success" asp-route-id="@Model">Sczegóły</a>
        <a asp-action="Delete" asp-controller="SpecialTag" class="btn btn-danger" asp-route-id="@Model">Usuń</a>
    </div>
</td>